# -*- coding: utf-8 -*-
"""Proyek Analisis Data_Aditya Dwi Putra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvyHMIi0amlYjOV25o-Qo4J8MrcHLWOW

# Proyek Analisis Data: [Bike Sharing Dataset]
- **Nama:** [Aditya Dwi Putra]
- **Email:** [dwipa270400@gmail.com]
- **ID Dicoding:** [adityadwiputra]

## Menentukan Pertanyaan Bisnis

- Bagaimana pola penggunaan Bike Sharing di sepanjang hari?
- Faktor apa saja yang paling memengaruhi jumlah penyewaan sepeda pada hari kerja dan akhir pekan?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

# Step 1: Gathering Data
# Load datasets
day_df = pd.read_csv('/mnt/data/day.csv')
hour_df = pd.read_csv('/mnt/data/hour.csv')

"""**Insight:**
- Berguna untuk memuat data yang akan digunakan

### Assessing Data
"""

# Step 2: Assessing Data
# Display first few rows of both datasets
print("Day Dataset Head:")
print(day_df.head())
print("\nHour Dataset Head:")
print(hour_df.head())

# Display summary information for both datasets
print("\nDay Dataset Info:")
print(day_df.info())
print("\nHour Dataset Info:")
print(hour_df.info())

# Check for missing values
print("\nMissing Values in Day Dataset:")
print(day_df.isnull().sum())
print("\nMissing Values in Hour Dataset:")
print(hour_df.isnull().sum())

# Check for duplicates
print("\nDuplicates in Day Dataset:", day_df.duplicated().sum())
print("\nDuplicates in Hour Dataset:", hour_df.duplicated().sum())

"""**Insight:**
- Berguna untuk membaca data
- Berguna untuk memeriksa data yang hilang
- Berguna untuk memeriksa duplikat data

### Cleaning Data
"""

# Step 3: Cleaning Data
# Drop duplicates if any
day_df.drop_duplicates(inplace=True)
hour_df.drop_duplicates(inplace=True)

# Ensure correct data types for columns
for df in [day_df, hour_df]:
    df['dteday'] = pd.to_datetime(df['dteday'])

print("\nData Cleaning Completed!")

"""**Insight:**
- Berguna untuk pembersihan data, jika ada data duplikat maka akan terhapus
- Memastikan data benar-benar bersih

## Exploratory Data Analysis (EDA)

### Explore ...
"""

# Step 4: Exploratory Data Analysis (EDA)
# Explore general trends in day_df
print("\nSummary Statistics for Day Dataset:")
print(day_df.describe())

print("\nSummary Statistics for Hour Dataset:")
print(hour_df.describe())

# Visualize rental counts over time in day_df
plt.figure(figsize=(12, 6))
plt.plot(day_df['dteday'], day_df['cnt'], label='Daily Total Rentals', color='blue')
plt.title('Daily Total Rentals Over Time')
plt.xlabel('Date')
plt.ylabel('Total Rentals (cnt)')
plt.legend()
plt.show()

# Visualize rental counts by hour in hour_df
hourly_counts = hour_df.groupby('hr')['cnt'].mean()
plt.figure(figsize=(10, 5))
plt.bar(hourly_counts.index, hourly_counts.values, color='skyblue')
plt.title('Average Hourly Rentals')
plt.xlabel('Hour')
plt.ylabel('Average Rentals')
plt.xticks(range(0, 24))
plt.show()

"""**Insight:**
- Berguna untuk mengeksplor tren atau pola yang diamati dari plot

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

# Step 5: Visualization & Explanatory Analysis
# Visualization for Question 1: Patterns by hour
plt.figure(figsize=(12, 6))
sns.boxplot(x='hr', y='cnt', data=hour_df, palette='Blues')
plt.title('Distribution of Rentals by Hour')
plt.xlabel('Hour of the Day')
plt.ylabel('Total Rentals (cnt)')
plt.show()

"""### Pertanyaan 2:"""

# Visualization for Question 2: Factors affecting rentals (day_df)
plt.figure(figsize=(10, 6))
sns.heatmap(day_df[['cnt', 'temp', 'atemp', 'hum', 'windspeed']].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap for Key Factors')
plt.show()

# Comparison of rentals on weekdays vs weekends
plt.figure(figsize=(10, 6))
sns.barplot(x='weekday', y='cnt', data=day_df, ci=None, palette='viridis')
plt.title('Average Rentals by Day of the Week')
plt.xlabel('Day of the Week (0 = Sunday, 6 = Saturday)')
plt.ylabel('Average Rentals')
plt.show()

"""**Insight:**
- Menampilkan gambaran pola penggunaan Bike Sharing di sepanjang hari
- Menampilkan faktor yang paling memengaruhi jumlah penyewaan sepeda pada hari kerja dan akhir pekan

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Pengelola layanan dapat memastikan ketersediaan sepeda yang lebih tinggi selama jam sibuk pada hari kerja. Strategi seperti menambah stasiun sepeda di kawasan perkantoran dapat membantu memenuhi kebutuhan ini.
- Cuaca adalah faktor kunci dalam memprediksi penggunaan sepeda. Penyedia layanan dapat menggunakan prediksi cuaca untuk mengatur jumlah sepeda yang tersedia. Selain itu, promosi di akhir pekan dapat meningkatkan jumlah penyewaan dari pengguna kasual.
"""